services:
  backend:
    build:
      context: ./notes-backend
      dockerfile: Dockerfile
    container_name: notes-backend
    ports:
      - "8080:8080"
    environment:
      NOTES_SERVER_PORT: 8080
      NOTES_DB_HOST: localhost
      NOTES_DB_PORT: 5432
      NOTES_DB_NAME: notes-db
      NOTES_DB_USERNAME: postgres
      NOTES_DB_PASSWORD: Admin@123
    networks:
      - notes-network

  frontend:
    build:
      context: ./notes-frontend
      dockerfile: Dockerfile
    container_name: notes-frontend
    ports:
      - "3000:80"
    environment:
      API_BASE_URL: http://backend:8080
    depends_on:
      - backend
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge
